export const REMOVE_MEDITATION = "REMOVE_MEDITATION";
export const SET_CURRENT_MEDITATION = "SET_CURRENT_MEDITATION";
export const ADD_MEDITATION = "ADD_MEDITATION";
export const LOADING = "LOADING";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const UPDATE_FAVORITES = "UPDATE_FAVORITES";